# Generated by Django 4.1.13 on 2023-11-29 07:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='categories_interested',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='location_place',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='categories',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='numberOfChildren',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='placeLocation',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='placeOfBirth',
            field=djongo.models.fields.JSONField(default=dict, max_length=255),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='status',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='children',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.customer'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='sports',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
